#!/usr/bin/env python3

persistent_workspace_id_default = "PERSISTENT_WORKSPACE"
workspace_count_default = 5
keep_open_command_default = "alacritty -t $title"

persistent_workspace_id = input("Persistent workspace identifier [default={default}] ".format(default=persistent_workspace_id_default)) or persistent_workspace_id_default
workspace_count = input("How many workspaces would you like to keep open? [default={default}] ".format(default=workspace_count_default)) or workspace_count_default
keep_open_command = input("What command to run in each workspace? $title is substituted. [default={default}] ".format(default=keep_open_command_default)) or keep_open_command_default


result = "\n\n# Auto-generated by `hyprland-persistent-workspaces`\n"

# Global persistent workspace rules
result += "# Global persistent workspace rules \n"

configs = [
    'float',
    'nofocus',
    'noblur',
    'size 0 0',
    'move 0 0',
    'opacity 0'    
]

for config in configs:
    result += "windowrule={config},title:^{persistent_workspace_id}.*$\n".format(
        config=config,
        persistent_workspace_id=persistent_workspace_id
    )


result += "# Individual persistent workspace rules\n"

def get_workspace_id(i):
    return "{workspace_id}_{i}".format(workspace_id=persistent_workspace_id, i=i)

for i in range(1, int(workspace_count)+1):
    workspace_id = get_workspace_id(i)
    result += "windowrule=workspace {i},title:^({workspace_id})$\n".format(i=i,workspace_id=workspace_id)

result += "# Exec commands to keep each workspace persistent \n"

for i in range(1, int(workspace_count)+1):
    workspace_id = get_workspace_id(i)
    command = keep_open_command.replace("$title", workspace_id)
    result += "exec-once={command} & \n".format(command=command)

print(result)
